### PR TITLE
Support for Debian & Ubuntu

### PR DESCRIPTION
**Pull request by igalic**
A colleague of mine created a patch for debian & ubuntu
I've cleaned it up, rebased it and fixed the tests

### CODE REVIEW

**Comment by cschroer** [comment]
Any chance to see this merged? :)

**Comment by cristifalcas** [comment]
Sorry, I forgot about this PR.

Sure, I will be glade to merge this. Could you ask your colleague to try to fix the conflicts?

**Comment by igalic** [comment]
will rebase my rebase then you can merge :D

**Comment by cristifalcas** [comment]
I will make a new push with the changes from this PR. Please ask you colleague to check if I didn't misted something.

**Comment by igalic** [comment]
dd6701b2c5c18fb8be8d234b44098f5c2d4c1244 looks pretty good to me!

**Pull request closed without merging**
